### PR TITLE
Package structure refactoring

### PR DESCRIPTION
**Pull request by RoM4iK**
Hi. I want to suggest some additions to the package structure.
1. Git ignore distribution files, rename `lib` directory to `dist`, to avoid confusing.
2. Replace `es-2015` preset with the modern [preset-env](http://babeljs.io/docs/plugins/preset-env/)
3. Add yarn.lock to package.

### CODE REVIEW

**Comment by RoM4iK** [comment]
Also, I thought about moving from `ava` to `jest` test framework, and start writing contextless tests for all methods.

**Comment by siddharthkp** [comment]
Agree with point 1 and 2.

I'm excited about using npm5 with shrinkwrap instead of yarn

**Comment by siddharthkp** [comment]
Snapshot testing will remove a lot of work that has to go into tests right now. 

That doesn't necessarily mean jest though, ava has snapshot testing too :)

**Comment by RoM4iK** [comment]
I pointed on jest, not because of snapshot testing, because of common syntax to a lot of developers (describe blocks, expect). And also, I didn't found anything about mocking in ava.

**Comment by RoM4iK** [comment]
Replaced `yarn.lock` with shrinkwrap

**Comment by siddharthkp** [comment]
Sorry, it's taking me a while to get back to this. Have been swamped. Will test and merge this real soon.

**Comment by RoM4iK** [comment]
Okay, great.

**Pull request merged**
