### PR TITLE
Prettify + add precommit script

### PR DESCRIPTION
**Pull request by siddharthkp**
Using default prettier settings

### CODE REVIEW

**Comment by RoM4iK** [comment]
Great. I think prettier here can be replaced with https://github.com/prettier/prettier-eslint , and it should be added to package dev dependencies, to avoid confusion for contributors.
This will allow us to drop prettier configuration, and configure style in `.eslintrc`.

**Comment by siddharthkp** [comment]
@RoM4iK I intentionally didn't do that, because there are just 4 relevant settings. 

And with the pre-commit hook, we might not need eslint at all. Less tooling = less to fuss over 😄

**Comment by RoM4iK** [comment]
It makes sense, then I can only ask to add `trailingComma: "es5"` rule, everything else is good.

**Comment by siddharthkp** [comment]
@RoM4iK done!

**Comment by RoM4iK** [comment]
Awesome, let's merge it.

**Pull request merged**
